### ISSUE TITLE
Bottleneck in showing the search results

### ISSUE THREAD

**Issue by blokhin** [tilde-lab/optimade.science#30]
It seems there's a bottleneck in showing the search results, by the slowest provider. Until it returns the results, no other much faster providers' results are shown. This is strange, since the [Optimade client](https://github.com/tilde-lab/optimade) per se is asynchronous.

**Comment by PaulMaly** [comment]
It's not really strange, because asynchronous is not Optimade client, but http requests to optimade APIs. As a consumer of Optimade client, we want to get a full list of providers/structures from the whole hierarchy of APIs. One of the reasons for that is because Optimade client shouldn't try to assume which type of consumer use it. Some types of consumers just may not support some progressive form of data recieving. In addition, such a task will require the implementation of some kind of reactivity, e.g. observables to ship the data partially when it's ready.
